# Generated by Django 2.0.3 on 2018-04-10 22:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания записи')),
                ('user_time', models.DateTimeField(blank=True, null=True, verbose_name='Время анализа')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Масса')),
                ('min_size', models.DecimalField(decimal_places=5, max_digits=5, verbose_name='Минимальный размер')),
            ],
        ),
        migrations.CreateModel(
            name='CinderMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fractional_app.Measurement')),
            ],
            bases=('fractional_app.measurement',),
        ),
        migrations.CreateModel(
            name='SchiehtMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fractional_app.Measurement')),
            ],
            bases=('fractional_app.measurement',),
        ),
        migrations.AddField(
            model_name='weight',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='fractional_app.Measurement'),
        ),
        migrations.AddField(
            model_name='measurementpair',
            name='cinder',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pair', to='fractional_app.CinderMeasurement'),
        ),
        migrations.AddField(
            model_name='measurementpair',
            name='schieht',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pair', to='fractional_app.SchiehtMeasurement'),
        ),
    ]
