# Generated by Django 2.0.7 on 2018-07-18 17:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import furnace.fractional_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания записи')),
                ('user_time', models.DateTimeField(blank=True, null=True, verbose_name='Время анализа')),
            ],
            options={
                'verbose_name': 'Измерение',
                'verbose_name_plural': 'Измерения',
            },
        ),
        migrations.CreateModel(
            name='MeasurementPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name=furnace.fractional_app.models.SchiehtMeasurement)),
            ],
            options={
                'verbose_name': 'Пара измерений',
                'verbose_name_plural': 'Пары измерений',
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField(blank=True, null=True, verbose_name='Масса')),
                ('min_size', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Минимальный размер')),
            ],
            options={
                'verbose_name': 'Вес',
                'verbose_name_plural': 'Веса',
                'ordering': ['min_size'],
            },
        ),
        migrations.CreateModel(
            name='CinderMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fractional_app.Measurement')),
            ],
            options={
                'verbose_name': 'Измерение гранулярного состава огарка',
                'verbose_name_plural': 'Измерения гранулярного состава огарка',
            },
            bases=('fractional_app.measurement',),
        ),
        migrations.CreateModel(
            name='SchiehtMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fractional_app.Measurement')),
            ],
            options={
                'verbose_name': 'Измерение гранулярного состава шихты',
                'verbose_name_plural': 'Измерения гранулярного состава шихты',
            },
            bases=('fractional_app.measurement',),
        ),
        migrations.AddField(
            model_name='weight',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='fractional_app.Measurement'),
        ),
        migrations.AddField(
            model_name='measurementpair',
            name='cinder',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pair', to='fractional_app.CinderMeasurement', verbose_name='Огарок'),
        ),
        migrations.AddField(
            model_name='measurementpair',
            name='schieht',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pair', to='fractional_app.SchiehtMeasurement', verbose_name='Шихта'),
        ),
    ]
