# Generated by Django 2.0.3 on 2018-04-11 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fractional_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['min_size']},
        ),
        migrations.AlterField(
            model_name='weight',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='fractional_app.Measurement'),
        ),
    ]
