# Generated by Django 2.0.3 on 2018-04-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fractional_app', '0002_auto_20180411_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='mass',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса'),
        ),
    ]
