# Generated by Django 2.0.3 on 2018-04-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fractional_app', '0003_auto_20180411_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='min_size',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Минимальный размер'),
        ),
    ]
