# Generated by Django 2.0.3 on 2018-04-19 19:04

from django.db import migrations, models
import furnace.fractional_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('fractional_app', '0004_auto_20180411_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementpair',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=furnace.fractional_app.models.SchiehtMeasurement),
        ),
    ]
