from e_logs.common.all_journals_app.models import Journal, Table


def fill_tables():
    
    leaching_express_analysis_journal = Journal.objects.get(name='leaching_express_analysis')
    leaching_repair_equipment_journal = Journal.objects.get(name='leaching_repair_equipment')
    concentrate_report_journal = Journal.objects.get(name='concentrate_report')
    report_income_outcome_schieht_journal = Journal.objects.get(name='report_income_outcome_schieht')
    metals_compute_journal = Journal.objects.get(name='metals_compute')
    technological_tasks_journal = Journal.objects.get(name='technological_tasks')
    furnace_repair_journal = Journal.objects.get(name='furnace_repair')
    furnace_changed_fraction_journal = Journal.objects.get(name='furnace_changed_fraction')
    electrolysis_technical_report_4_degree_journal =\
        Journal.objects.get(name='electrolysis_technical_report_4_degree')
    electrolysis_technical_report_3_degree_journal =\
        Journal.objects.get(name='electrolysis_technical_report_3_degree')
    electrolysis_technical_report_12_degree_journal =\
        Journal.objects.get(name='electrolysis_technical_report_12_degree')
    electrolysis_repair_report_tables_journal =\
        Journal.objects.get(name='electrolysis_repair_report_tables')
    masters_report_journal = Journal.objects.get(name='masters_report')
    reports_furnace_area_journal = Journal.objects.get(name='reports_furnace_area')

    Table.objects.bulk_create([
        Table(
            name='vsns',
            journal=leaching_express_analysis_journal
        ),
        Table(
            name='thickeners',
            journal=leaching_express_analysis_journal
        ),
        Table(
            name='zinc_pulp',
            journal=leaching_express_analysis_journal
        ),
        Table(
            name='appt_hydrometal',
            journal=leaching_express_analysis_journal
        ),
        Table(
            name='agitators',
            journal=leaching_express_analysis_journal
        ),
        Table(
            name='reagents',
            journal=leaching_express_analysis_journal
        ),
        Table(
            name='neutral_thickeners',
            journal=leaching_express_analysis_journal
        ),
        Table(
            name='tanks_availability',
            journal=leaching_express_analysis_journal
        ),
        Table(
            name='tanks_for_finished_products',
            journal=leaching_express_analysis_journal
        ),
        Table(
            name='self_protection',
            journal=leaching_express_analysis_journal
        ),
        Table(
            name='cinder',
            journal=leaching_express_analysis_journal
        ),
        Table(
            name='sample',
            journal=leaching_express_analysis_journal
        ),
        Table(
            name='loads',
            journal=leaching_express_analysis_journal
        ),
        Table(
            name='neutral',
            journal=leaching_express_analysis_journal
        ),
        Table(
            name='shift_info',
            journal=leaching_express_analysis_journal
        ),
        Table(
            name='repair',
            journal=leaching_repair_equipment_journal
        ),
        Table(
            name='big',
            journal=concentrate_report_journal
        ),
        Table(
            name='small',
            journal=concentrate_report_journal
        ),
        Table(
            name='upper',
            journal=concentrate_report_journal
        ),
        Table(
            name='lower',
            journal=concentrate_report_journal
        ),
        Table(
            name='main',
            journal=report_income_outcome_schieht_journal
        ),
        Table(
            name='supply_of_zinc_concentrates',
            journal=report_income_outcome_schieht_journal
        ),
        Table(
            name='year_plan_schieht',
            journal=report_income_outcome_schieht_journal
        ),
        Table(
            name='summary',
            journal=report_income_outcome_schieht_journal
        ),
        Table(
            name='main',
            journal=metals_compute_journal
        ),
        Table(
            name='sns',
            journal=metals_compute_journal
        ),
        Table(
            name='sgok',
            journal=metals_compute_journal
        ),
        Table(
            name='gof',
            journal=metals_compute_journal
        ),
        Table(
            name='avg_month',
            journal=metals_compute_journal
        ),
        Table(
            name='cinder_conc',
            journal=metals_compute_journal
        ),
        Table(
            name='concentrat',
            journal=metals_compute_journal
        ),
        Table(
            name='contain_zn',
            journal=metals_compute_journal
        ),
        Table(
            name='main',
            journal=technological_tasks_journal
        ),
        Table(
            name='repair',
            journal=furnace_repair_journal
        ),
        Table(
            name='main',
            journal=furnace_changed_fraction_journal
        ),
        Table(
            name='left',
            journal=electrolysis_technical_report_4_degree_journal
        ),
        Table(
            name='right',
            journal=electrolysis_technical_report_4_degree_journal
        ),
        Table(
            name='left',
            journal=electrolysis_technical_report_3_degree_journal
        ),
        Table(
            name='right',
            journal=electrolysis_technical_report_3_degree_journal
        ),
        Table(
            name='left',
            journal=electrolysis_technical_report_12_degree_journal
        ),
        Table(
            name='right',
            journal=electrolysis_technical_report_12_degree_journal
        ),
        Table(
            name='main',
            journal=electrolysis_repair_report_tables_journal
        ),
        Table(
            name='seria1',
            journal=masters_report_journal
        ),
        Table(
            name='seria3',
            journal=masters_report_journal
        ),
        Table(
            name='seria4',
            journal=masters_report_journal
        ),
        Table(
            name='params',
            journal=masters_report_journal
        ),
        Table(
            name='melt_area1',
            journal=masters_report_journal
        ),
        Table(
            name='melt_area2',
            journal=masters_report_journal
        ),
        Table(
            name='zinc',
            journal=masters_report_journal
        ),
        Table(
            name='last',
            journal=masters_report_journal
        ),
        Table(
            name='main',
            journal=reports_furnace_area_journal
        ),
        Table(
            name='udel',
            journal=reports_furnace_area_journal
        ),
        Table(
            name='area_class_cinder',
            journal=reports_furnace_area_journal
        ),
        Table(
            name='electrofilter',
            journal=reports_furnace_area_journal
        ),
        Table(
            name='warehouse_concentrates',
            journal=reports_furnace_area_journal
        ),
        Table(
            name='airmachines',
            journal=reports_furnace_area_journal
        ),
        Table(
            name='fences',
            journal=reports_furnace_area_journal
        ),
        Table(
            name='concentration_by_time',
            journal=reports_furnace_area_journal
        ),
        Table(
            name='places_of_sampling',
            journal=reports_furnace_area_journal
        ),
        Table(
            name='corrective_actions',
            journal=reports_furnace_area_journal
        ),
        Table(
            name='self_protection',
            journal=reports_furnace_area_journal
        ),
        Table(
            name='worth',
            journal=reports_furnace_area_journal
        ),
    ])
