# Generated by Django 2.0.5 on 2018-07-06 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=128, verbose_name='Название таблицы')),
                ('field_name', models.CharField(max_length=128, verbose_name='Название поля')),
                ('index', models.IntegerField(blank=True, default=None, null=True, verbose_name='Номер строчки')),
                ('value', models.CharField(max_length=1024, verbose_name='Значение поля')),
            ],
        ),
        migrations.CreateModel(
            name='JournalPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('shift', 'Смена'), ('equipment', 'Оборудование'), ('month', 'Месяц')], max_length=128)),
                ('journal_name', models.CharField(max_length=256, verbose_name='Название журнала')),
                ('shift_order', models.IntegerField(blank=True, verbose_name='Номер смены')),
                ('shift_date', models.DateField(blank=True, verbose_name='Дата начала смены')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('leaching', 'Выщелачивание'), ('furnace', 'Обжиг'), ('electrolysis', 'Электролиз')], default='leaching', max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='journalpage',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='all_journals_app.Plant'),
        ),
        migrations.AddField(
            model_name='cellvalue',
            name='journal_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_journals_app.JournalPage'),
        ),
        migrations.AddField(
            model_name='cellvalue',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.Employee'),
        ),
        migrations.AlterUniqueTogether(
            name='journalpage',
            unique_together={('plant', 'shift_order', 'shift_date', 'journal_name')},
        ),
    ]
