# Generated by Django 2.1.2 on 2018-10-12 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_journals_app', '0001_initial'),
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.Employee'),
        ),
        migrations.AddField(
            model_name='cellgroup',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_journals_app.Journal'),
        ),
        migrations.AddField(
            model_name='cell',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='all_journals_app.Field'),
        ),
        migrations.AddField(
            model_name='cell',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_cells', to='all_journals_app.CellGroup'),
        ),
        migrations.AddField(
            model_name='cell',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.Employee'),
        ),
        migrations.AddField(
            model_name='shift',
            name='responsibles',
            field=models.ManyToManyField(to='login_app.Employee'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['name'], name='all_journal_name_02bc46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('field', 'index', 'group')},
        ),
    ]
