# Generated by Django 2.0.6 on 2018-08-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
        ('all_journals_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.Employee'),
        ),
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('field', 'index', 'group')},
        ),
    ]
