# Generated by Django 2.0.6 on 2018-08-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0002_auto_20180806_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='comment',
            field=models.CharField(default='', max_length=1024, verbose_name='Комментарий к ячейке'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='value',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Значение поля'),
        ),
        migrations.AlterField(
            model_name='cellgroup',
            name='name',
            field=models.CharField(default='', max_length=1024, verbose_name='Название группы ячеек'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(choices=[('leaching', 'Выщелачивание'), ('furnace', 'Обжиг'), ('electrolysis', 'Электролиз')], default='leaching', max_length=128),
        ),
    ]
