# Generated by Django 2.0.6 on 2018-08-21 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0002_auto_20180815_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='all_journals_app.CellGroup'),
        ),
    ]
