# Generated by Django 2.0.6 on 2018-07-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0002_cell_responsible'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('table_name', 'field_name', 'index', 'group')},
        ),
    ]
