# Generated by Django 2.1.2 on 2018-10-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0002_auto_20181012_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='units',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
