# Generated by Django 2.0.7 on 2018-08-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0002_auto_20180815_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
    ]
