# Generated by Django 2.0.7 on 2018-08-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0002_auto_20180812_1303'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['name'], name='all_journal_name_02bc46_idx'),
        ),
    ]
