# Generated by Django 2.1.2 on 2018-10-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0002_auto_20181002_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='formula',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='Формула'),
        ),
    ]
