# Generated by Django 2.1.3 on 2018-11-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0002_auto_20181024_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='order',
            field=models.IntegerField(verbose_name='Порядок смены'),
        ),
    ]
