# Generated by Django 2.0.7 on 2018-08-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0002_auto_20180810_1847'),
        ('all_journals_app', '0002_auto_20180810_2138'),
        ('all_journals_app', '0002_auto_20180810_1859'),
    ]

    operations = [
    ]
