# Generated by Django 2.1.2 on 2018-11-12 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0003_auto_20181106_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthGroup',
            fields=[
                ('cellgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='all_journals_app.CellGroup')),
                ('month', models.CharField(max_length=16, verbose_name='Месяц')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
            ],
            bases=('all_journals_app.cellgroup',),
        ),
        migrations.CreateModel(
            name='YearGroup',
            fields=[
                ('cellgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='all_journals_app.CellGroup')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
            ],
            bases=('all_journals_app.cellgroup',),
        ),
        migrations.RenameModel(
            old_name='Equipment',
            new_name='EquipmentGroup',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='cellgroup_ptr',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
