# Generated by Django 2.0.7 on 2018-08-11 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0003_merge_20180811_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='all_journals_app.Field'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(choices=[('leaching', 'Выщелачивание'), ('furnace', 'Обжиг'), ('electrolysis', 'Электролиз')], default='leaching', max_length=128, verbose_name='Название цеха'),
        ),
    ]
