# Generated by Django 2.0.7 on 2018-08-15 16:18

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0003_auto_20180815_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=1, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cell',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
