# Generated by Django 2.1 on 2018-08-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0003_auto_20180821_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
