# Generated by Django 2.0.5 on 2018-07-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0004_auto_20180712_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Пользователь'),
        ),
    ]
