# Generated by Django 2.1 on 2018-09-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0004_shift_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='verbose_name',
            field=models.CharField(default=' ', max_length=256, verbose_name='Название журнала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Журнал'),
        ),
    ]
