# Generated by Django 2.0.7 on 2018-08-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0004_auto_20180815_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='modified',
        ),
    ]
