# Generated by Django 2.1.2 on 2018-11-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0004_auto_20181112_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthgroup',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='yeargroup',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
