# Generated by Django 2.1.2 on 2018-11-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0005_auto_20181112_2204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipmentGroup',
            new_name='Equipment',
        ),
        migrations.RenameModel(
            old_name='MonthGroup',
            new_name='Month',
        ),
        migrations.RenameModel(
            old_name='YearGroup',
            new_name='Year',
        ),
        migrations.RenameField(
            model_name='month',
            old_name='month',
            new_name='month_date',
        ),
        migrations.RenameField(
            model_name='month',
            old_name='year',
            new_name='year_date',
        ),
        migrations.RenameField(
            model_name='year',
            old_name='year',
            new_name='year_date',
        ),
    ]
