# Generated by Django 2.1 on 2018-09-05 12:30

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0005_auto_20180904_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 5, 12, 30, 30, 786788, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cell',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
