# Generated by Django 2.1.2 on 2018-10-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0005_auto_20181023_2134'),
        ('all_journals_app', '0005_auto_20181023_1627'),
    ]

    operations = [
    ]
