# Generated by Django 2.1.2 on 2018-10-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_remove_employee_owned_shifts'),
        ('all_journals_app', '0005_auto_20181006_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='responsibles',
            field=models.ManyToManyField(to='login_app.Employee'),
        ),
    ]
