# Generated by Django 2.1 on 2018-09-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0006_auto_20180905_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='verbose_name',
            field=models.CharField(default='', max_length=256, verbose_name='Название столбца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='verbose_name',
            field=models.CharField(default='', max_length=256, verbose_name='Название таблицы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Столбец'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Таблица'),
        ),
    ]
