# Generated by Django 2.1.2 on 2018-11-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0006_auto_20181113_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='month_order',
            field=models.IntegerField(default=1, verbose_name='Номер месяца'),
            preserve_default=False,
        ),
    ]
