# Generated by Django 2.1.2 on 2018-10-24 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0006_merge_20181024_0639'),
        ('all_journals_app', '0006_merge_20181024_0057'),
    ]

    operations = [
    ]
