# Generated by Django 2.0.5 on 2018-07-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0006_merge_20180712_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('value', models.CharField(max_length=128, verbose_name='Значение')),
                ('plant', models.CharField(max_length=128, verbose_name='Цех')),
                ('journal', models.CharField(max_length=128, verbose_name='Журнал')),
                ('table', models.CharField(max_length=128, verbose_name='Таблица')),
                ('cell', models.CharField(max_length=128, verbose_name='Ячейка')),
            ],
        ),
    ]
