# Generated by Django 2.0.5 on 2018-07-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0007_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='cell',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ячейка'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='journal',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Журнал'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='plant',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Цех'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='table',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Таблица'),
        ),
    ]
