# Generated by Django 2.1 on 2018-09-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0007_auto_20180906_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='verbose_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Название столбца'),
        ),
    ]
