# Generated by Django 2.0.6 on 2018-07-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0008_auto_20180720_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellvalue',
            name='responsible',
        ),
    ]
