# Generated by Django 2.0.5 on 2018-07-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0008_auto_20180720_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
