# Generated by Django 2.1 on 2018-09-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0009_shift_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='verbose_name',
            field=models.CharField(default='', max_length=128, verbose_name='Название цеха'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(choices=[('leaching', 'Выщелачивание'), ('furnace', 'Обжиг'), ('electrolysis', 'Электролиз')], default='leaching', max_length=128, verbose_name='Цех'),
        ),
    ]
