# Generated by Django 2.0.6 on 2018-07-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0009_remove_cellvalue_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellvalue',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
