# Generated by Django 2.1.3 on 2018-11-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0009_auto_20181119_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=2048, verbose_name='Название папки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='all_journals_app.MenuFolder')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='all_journals_app.MenuFolder'),
        ),
    ]
