# Generated by Django 2.0.5 on 2018-07-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0009_delete_feedback'),
        ('all_journals_app', '0009_remove_cellvalue_responsible'),
    ]

    operations = [
    ]
