# Generated by Django 2.0.6 on 2018-07-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0010_cellvalue_created_on'),
        ('all_journals_app', '0010_merge_20180724_1553'),
    ]

    operations = [
    ]
