# Generated by Django 2.1.3 on 2018-11-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0010_auto_20181121_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='parent',
            new_name='folder',
        ),
        migrations.AddField(
            model_name='cellgroup',
            name='journal_path',
            field=models.FilePathField(default='/', match='*.jrn', path='resources/journals', recursive=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cellgroup',
            name='version',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
