# Generated by Django 2.1 on 2018-09-21 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0010_auto_20180920_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_cells', to='all_journals_app.CellGroup'),
        ),
    ]
