# Generated by Django 2.1.3 on 2018-11-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0011_auto_20181122_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellgroup',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
