# Generated by Django 2.0.6 on 2018-07-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0011_merge_20180724_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellvalue',
            name='created_on',
        ),
        migrations.AddField(
            model_name='journalpage',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
    ]
