# Generated by Django 2.0.6 on 2018-07-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0012_auto_20180724_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalpage',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время'),
        ),
    ]
