# Generated by Django 2.0.6 on 2018-07-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0014_auto_20180725_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
