# Generated by Django 2.1 on 2018-10-02 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import e_logs.core.utils.webutils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_journals_app', '0001_initial'),
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('critical_value', 'Критическое значение'), ('comment', 'Замечание'), ('set_mode', 'Режим'), ('blank_journal', 'Пустой журнал')], default='', max_length=1024, verbose_name='Тип сообщения')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('link', models.URLField(default='#', max_length=1024, null=True, verbose_name='Ссылка на ячейку')),
                ('addressee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_addressee', to='login_app.Employee')),
                ('cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_journals_app.Cell')),
                ('sendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sendee', to='login_app.Employee')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
            bases=(e_logs.core.utils.webutils.StrAsDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='login_app.Employee')),
            ],
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', 'addressee'], name='messages_ap_is_read_dff508_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['addressee'], name='messages_ap_address_d05365_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created'], name='messages_ap_created_5ef8d3_idx'),
        ),
    ]
