# Generated by Django 2.0.7 on 2018-08-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', 'addressee'], name='messages_ap_is_read_dff508_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['addressee'], name='messages_ap_address_d05365_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created'], name='messages_ap_created_5ef8d3_idx'),
        ),
    ]
