# Generated by Django 2.0.6 on 2018-07-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='cell_link',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='message',
            name='cell_field_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='cell_journal_page',
        ),
        migrations.RemoveField(
            model_name='message',
            name='cell_table_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='row_index',
        ),
    ]
