# Generated by Django 2.1.3 on 2018-11-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('critical_value', 'Критическое значение'), ('comment', 'Замечание'), ('set_mode', 'Режим'), ('blank_journal', 'Пустой журнал')], default='', max_length=32, verbose_name='Тип сообщения'),
        ),
    ]
