# Generated by Django 2.0.6 on 2018-08-23 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='addressee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_addressee', to='login_app.Employee'),
        ),
        migrations.AlterField(
            model_name='message',
            name='link',
            field=models.URLField(default='#', max_length=1024, null=True, verbose_name='Ссылка на ячейку'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('critical_value', 'Критическое значение'), ('comment', 'Замечание'), ('set_mode', 'Режим')], default='', max_length=1024, verbose_name='Тип сообщения'),
        ),
    ]
