# Generated by Django 2.0.7 on 2018-08-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='link',
            field=models.URLField(default='#', max_length=1024, verbose_name='Ссылка на ячейку'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('critical_value', 'Критическое значение'), ('comment', 'Замечание')], default='', max_length=1024, verbose_name='Тип сообщения'),
        ),
    ]
