# Generated by Django 2.0.6 on 2018-08-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('critical_value', 'Критическое значение'), ('comment', 'Замечание')], default='', max_length=100, verbose_name='Тип сообщения'),
        ),
    ]
