# Generated by Django 2.0.7 on 2018-07-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_auto_20180718_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cell_link',
            field=models.URLField(default='#', max_length=128, verbose_name='Ссылка на ячейку'),
        ),
    ]
