# Generated by Django 2.0.6 on 2018-07-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0003_auto_20180727_1738'),
        ('messages_app', '0002_auto_20180727_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_journals_app.Cell'),
        ),
    ]
