# Generated by Django 2.1 on 2018-08-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_auto_20180823_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('critical_value', 'Критическое значение'), ('comment', 'Замечание'), ('set_mode', 'Режим'), ('blank_journal', 'Пустой журнал')], default='', max_length=1024, verbose_name='Тип сообщения'),
        ),
    ]
