# Generated by Django 2.0.5 on 2018-07-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0004_auto_20180724_0006'),
        ('messages_app', '0004_auto_20180724_1137'),
    ]

    operations = [
    ]
