<<<<<<< HEAD
# Generated by Django 2.0.6 on 2018-08-10 15:47
=======
# Generated by Django 2.0.7 on 2018-08-10 15:59
>>>>>>> 8bee91f09c7f8ba19c68907116b07e1eeb91fbc2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('value', models.CharField(max_length=2048, verbose_name='Значение')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_app.Employee')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together={('name', 'employee', 'content_type', 'object_id')},
        ),
    ]
