# Generated by Django 2.0.7 on 2018-08-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='setting',
            index=models.Index(fields=['name', 'employee'], name='core_settin_name_e38cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='setting',
            index=models.Index(fields=['name'], name='core_settin_name_b329f4_idx'),
        ),
        migrations.AddIndex(
            model_name='setting',
            index=models.Index(fields=['name', 'content_type', 'object_id'], name='core_settin_name_f9b029_idx'),
        ),
    ]
