# Generated by Django 2.1 on 2018-10-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='verbose_name',
            field=models.CharField(default='', max_length=256, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
    ]
