# Generated by Django 2.1.2 on 2018-10-24 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_app.Employee'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='setting',
            index=models.Index(fields=['name', 'employee'], name='core_settin_name_e38cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='setting',
            index=models.Index(fields=['name'], name='core_settin_name_b329f4_idx'),
        ),
        migrations.AddIndex(
            model_name='setting',
            index=models.Index(fields=['name', 'content_type', 'object_id'], name='core_settin_name_f9b029_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together={('name', 'employee', 'content_type', 'object_id')},
        ),
    ]
