# Generated by Django 2.1.3 on 2018-11-06 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181024_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', related_query_name='setting', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login_app.Employee'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Название'),
        ),
    ]
