# Generated by Django 2.0.6 on 2018-07-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180726_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(max_length=640, verbose_name='Значение'),
        ),
    ]
