# Generated by Django 2.1.2 on 2018-10-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='journal',
        ),
        migrations.AddField(
            model_name='feedback',
            name='filenames',
            field=models.TextField(default='', verbose_name='Имена файлов'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='plant',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цех'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='theme',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тема'),
        ),
    ]
