#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo Starting node...
exec npm start --prefix /e-logs-constructor/backend &

echo Starting node http server
cd /e-logs-constructor/frontend/dist
exec /e-logs-constructor/frontend/node_modules/http-server/bin/http-server -p 8003 ./ 

