numeric_default = dict(type="number")
date_default = dict(type="date")
month_default = dict(type="month")
time_default = dict(type="time", min_normal=10, max_normal=1000)
text_default = dict(type="text")
datalist_default = dict(type="datalist", options=[])

employee_default = dict(type="text", units='Фамилия И.О.')
pieces_default = dict(type="number", units='шт')
number_default = dict(type="number", units='№')
percent_default = dict(type = "number", units = '%')
temperature_default = dict(type="number", units="ᵒC")
tm2_day_default = dict(type="number", units='тм²/сут')
ton_default = dict(type="number", units='тонн')
gl_default = dict(type = "number", units = "г/л")
mgl_default = dict(type="number", units="мг/л")
amperage_default = dict(type="number", units="кА")
m3_default = dict(type="number", units="м³")
m3hour_default = dict(type="number", units="м³/час")
gsm3_default = dict(type="number", units="г/см³")
kgsm2_default = dict(type="number", units='кгс/м²')
m_default = dict(type="number", units="м")
vmt_default = dict(type="number", units="ВМТ")
smt_default = dict(type="number", units="СМТ")
gt_default = dict(type="number", units="г/т")
mm_vod_st_default = dict(type="number", units="мм. вод. ст.")
ob_min = dict(type="number", units="об/мин")
kg_default = dict(type="number", units="кг")
pa_default = dict(type="number", units="Па")
