from common.all_journals_app.fields_descriptions.tables.conc_raports_tables import *
from common.all_journals_app.fields_descriptions.tables.input_output_report import main_table_desc
from utils.deep_dict import deep_dict

fields_info_desc = deep_dict()

fields_info_desc.concentrate_report_journal.big_table = big_table_desc
fields_info_desc.concentrate_report_journal.small_table = small_table_desc
fields_info_desc.concentrate_report_journal.upper_fields = upper_table_desc
fields_info_desc.concentrate_report_journal.lower_fields = lower_table_desc

fields_info_desc.report_income_outcome_schieht.loading_schieht_table = main_table_desc
