# Generated by Django 2.0.7 on 2018-08-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['plant', 'position'], name='login_app_e_plant_2940c7_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['plant'], name='login_app_e_plant_70993a_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position'], name='login_app_e_positio_8631f6_idx'),
        ),
    ]
