# Generated by Django 2.1.2 on 2018-10-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='owned_shifts',
        ),
    ]
