# Generated by Django 2.1.2 on 2018-10-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='plant',
            field=models.CharField(choices=[('furnace', 'Обжиг'), ('leaching', 'Выщелачивание'), ('electrolysis', 'Электролиз'), (None, '-')], max_length=128, null=True, verbose_name='Цех'),
        ),
    ]
