# Generated by Django 2.1.2 on 2018-10-23 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20181023_1627'),
        ('login_app', '0004_auto_20181023_2134'),
    ]

    operations = [
    ]
