# Generated by Django 2.1.2 on 2018-10-24 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_merge_20181024_0056'),
        ('login_app', '0005_merge_20181024_0639'),
    ]

    operations = [
    ]
