# Generated by Django 2.1.2 on 2018-11-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Concentrate',
            new_name='ConcentrateDict',
        ),
        migrations.RenameModel(
            old_name='Equipment',
            new_name='EquipmentDict',
        ),
    ]
