# Generated by Django 2.1.3 on 2018-11-29 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_equipmentdict_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdict',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_journals_app.Plant'),
        ),
    ]
