# Generated by Django 2.1.3 on 2018-11-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0004_auto_20181129_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentratedict',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='equipmentdict',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
