numeric_default = dict(type="number")
date_default = dict(type="date")
month_default = dict(type="month")
time_default = dict(type="time")
text_default = dict(type="text")
datalist_default = dict(type="datalist", options=[])

employee_default = dict(type="text", units='Фамилия И.О.')
pieces_default = dict(type="number", units='шт')
number_default = dict(type="number", units='№')
percent_default = dict(type="number", units='%')
temperature_default = dict(type="number", units="ᵒC")
tm2_day_default = dict(type="number", units='тм²/сут')
ton_default = dict(type="number", units='тонн')
tn_default = dict(type="number", units='тн')
gl_default = dict(type="number", units="г/л")
mgl_default = dict(type="number", units="мг/л")
amperage_default = dict(type="number", units="кА")
m3_default = dict(type="number", units="м³")
voltage_default = dict(type="number", units="Вольт")
m3hour_default = dict(type="number", units="м³/час")
mhour_default = dict(type="number", units="м/час")
gsm3_default = dict(type="number", units="г/см³")
kgsm2_default = dict(type="number", units='кгс/м²')
mmwst_default = dict(type="number", units='мм.в.ст.')
m_default = dict(type="number", units="м")
vmt_default = dict(type="number", units="ВМТ")
smt_default = dict(type="number", units="СМТ")
sm_default = dict(type="number", units="см")
gt_default = dict(type="number", units="г/т")
mm_vod_st_default = dict(type="number", units="мм. вод. ст.")
mm_default = dict(type="number", units="мм")
ob_min = dict(type="number", units="об/мин")
kg_default = dict(type="number", units="кг")
pa_default = dict(type="number", units="Па")
ph_default = dict(type="number", units="pH")
amper_default = dict(type="number", units="Ампер")
