# Generated by Django 2.0.2 on 2018-03-05 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название журнала')),
                ('description', models.TextField(verbose_name='Описание таблицы')),
            ],
        ),
        migrations.CreateModel(
            name='JournalTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Время анализа/создания записи')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата начала смены')),
                ('order', models.DecimalField(decimal_places=0, max_digits=1, verbose_name='Номер смены (1, 2)')),
                ('plant', models.CharField(choices=[('0', 'обжиг'), ('1', 'выщелачивание'), ('2', 'электролиз')], max_length=1, verbose_name='Цех')),
            ],
        ),
        migrations.CreateModel(
            name='Agitators',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('before', models.BooleanField(verbose_name='До')),
                ('ph', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='pH')),
                ('cu', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Cu')),
                ('co', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Co')),
                ('cd', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Cd')),
                ('h2so4', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='H2SO4')),
                ('comment', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Комментарий')),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='CinderDensity',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('gran', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Ситовой огарка')),
                ('gran_avg', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Ситовой огарка средний')),
                ('fe_avg', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Общее Fe среднее')),
                ('fe_shave', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Fe Стружка Fe')),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='CuPulpAnal',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('liq_sol', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Ж:Т')),
                ('before', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='До')),
                ('after', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='После')),
                ('solid', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='ТВ')),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='DailyAnalysis',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('shlippe_sb', models.CharField(blank=True, max_length=64, verbose_name='Концентрация Sb в р-ре соли Шлиппе')),
                ('activ_sas', models.CharField(blank=True, max_length=64, verbose_name='Активность ПАВ')),
                ('circulation_denser', models.CharField(blank=True, max_length=64, verbose_name='Анализы оборот. сгуст.')),
                ('fe_hi1', models.CharField(blank=True, max_length=64, verbose_name='Высоко Fe р-р')),
                ('fe_hi2', models.CharField(blank=True, max_length=64, verbose_name='Высоко Fe р-р 2')),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='DenserAnal',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('point', models.CharField(choices=[('0', '10'), ('1', '11'), ('2', '12')], max_length=1, verbose_name='Сгуститель №')),
                ('sink', models.CharField(choices=[('0', 'ВС'), ('1', 'НС')], max_length=1, verbose_name='Слив')),
                ('ph', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='pH')),
                ('cu', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Cu')),
                ('fe', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Fe')),
                ('liq_sol', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Ж:Т')),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='Electrolysis',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('series', models.DateTimeField()),
                ('loads1', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('loads2', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('counter', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('bunkers_weltz', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('silos_furnace', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('bunkers_furnace', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='FeSolutionAnal',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('h2so4', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='H2SO4')),
                ('solid', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='ТВ')),
                ('sb', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Sb')),
                ('cu', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Cu')),
                ('fe', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Fe')),
                ('density', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Уд. вес')),
                ('arsenic', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='As')),
                ('cl', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Cl')),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='FreeTank',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('tank_name', models.CharField(blank=True, max_length=128)),
                ('prev_measure', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('deviation', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='HydroMetal',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('ph', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='pH')),
                ('acid', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Кисл-ть')),
                ('fe2', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Fe двухвал')),
                ('fe_total', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Fe общее')),
                ('cu', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Медь')),
                ('sb', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Сурьма')),
                ('sediment', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Отстой')),
                ('mann_num', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Манн №')),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='LeachingExpressAnal',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('point', models.CharField(choices=[('0', 'ВСНС'), ('1', 'Ларокс'), ('2', 'Очищенный раствор'), ('3', 'Упр. несоответствия продукции')], max_length=1, verbose_name='Место измерения')),
                ('co', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Co')),
                ('sb', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Sb')),
                ('cu', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Cu')),
                ('cu_st1', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Cu ст.1')),
                ('cd', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Cd')),
                ('solid_st1', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Cd')),
                ('ph', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='pH')),
                ('fe', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Fe')),
                ('arsenic', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='As')),
                ('solid', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Твердое г\\л')),
                ('current', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Выход по току')),
                ('density', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Уд. вес')),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='NeutralDenser',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('num', models.DateTimeField()),
                ('sediment', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('liq_sol1', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('liq_sol2', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='NeutralSolution',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('tank_name', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('value', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='ProductionErrors',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('norm', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Норма')),
                ('fact', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Факт')),
                ('error', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Несоответствие')),
                ('correction', models.CharField(max_length=512, verbose_name='Коррекция')),
                ('verified', models.BooleanField(default=False, verbose_name='Проверено')),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='ReadyProduct',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('num', models.DecimalField(blank=True, decimal_places=0, max_digits=1)),
                ('cd', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('cu', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('co', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('sb', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('fe', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('vt', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('density', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('norm', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('fact', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('correction', models.CharField(blank=True, max_length=128)),
                ('verified', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='Reagents',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('shlippe', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('zn', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('mg', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('magnaglobe', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('fe_shave', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('fence_state', models.CharField(blank=True, max_length=255)),
                ('delivered', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('accepted', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('consumption', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('taken_away', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('stage', models.CharField(choices=[('0', '1'), ('1', '2'), ('2', '3'), ('3', 'cd'), ('4', 'empty')], max_length=1)),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='Sample2',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('cd', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('cu', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='Schieht',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('num', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('name', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('value', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='SelfSecurity',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('note', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('bignote', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='ShiftInfo',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('out_sol_t', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('out_sol_c', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('out_pulp_cvck', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('out_cu_kek', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('out_cd_sponge', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('out_electr', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('out_ruch_cd', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('out_neutr', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('out_cu_pulp', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('in_filtrate_ls', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('in_filtrate_dens', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('in_fe', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('in_fe_hi', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('in_poor_cd', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='VEU',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('hot', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('cold', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=128)),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.CreateModel(
            name='ZnPulpAnal',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('liq_sol', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Ж:Т')),
                ('ph', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='pH')),
                ('t0', models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='t0')),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.AddField(
            model_name='journaltable',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='express_anal_app.Journal', verbose_name='Журнал'),
        ),
        migrations.AddField(
            model_name='journaltable',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='express_anal_app.Shift', verbose_name='Смена'),
        ),
    ]
