# Generated by Django 2.0.2 on 2018-03-05 15:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fesolutionanal',
            name='As',
        ),
        migrations.RemoveField(
            model_name='fesolutionanal',
            name='Cl',
        ),
        migrations.AddField(
            model_name='fesolutionanal',
            name='arsenic',
            field=models.DecimalField(blank=True, decimal_places=5, default=42.42, max_digits=10, verbose_name='As'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fesolutionanal',
            name='cl',
            field=models.DecimalField(blank=True, decimal_places=5, default=77.77, max_digits=10, verbose_name='Cl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала смены'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agitators',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.Employee'),
        ),
        migrations.AlterField(
            model_name='cinderdensity',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.Employee'),
        ),
        migrations.AlterField(
            model_name='cupulpanal',
            name='after',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='После'),
        ),
        migrations.AlterField(
            model_name='cupulpanal',
            name='before',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='До'),
        ),
        migrations.AlterField(
            model_name='cupulpanal',
            name='liq_sol',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Ж:Т'),
        ),
        migrations.AlterField(
            model_name='cupulpanal',
            name='solid',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='ТВ'),
        ),
        migrations.AlterField(
            model_name='denseranal',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Cu'),
        ),
        migrations.AlterField(
            model_name='denseranal',
            name='fe',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Fe'),
        ),
        migrations.AlterField(
            model_name='denseranal',
            name='liq_sol',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Ж:Т'),
        ),
        migrations.AlterField(
            model_name='denseranal',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='denseranal',
            name='point',
            field=models.CharField(choices=[('0', '10'), ('1', '11'), ('2', '12')], max_length=1, verbose_name='Сгуститель №'),
        ),
        migrations.AlterField(
            model_name='denseranal',
            name='sink',
            field=models.CharField(choices=[('0', 'ВС'), ('1', 'НС')], max_length=1, verbose_name='Слив'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Cu'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Уд. вес'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='fe',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Fe'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='h2so4',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='H2SO4'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='sb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Sb'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='solid',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='ТВ'),
        ),
        migrations.AlterField(
            model_name='hydrometal',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.Employee'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.TextField(verbose_name='Описание таблицы'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название журнала'),
        ),
        migrations.AlterField(
            model_name='journaltable',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='express_anal_app.Journal', verbose_name='Журнал'),
        ),
        migrations.AlterField(
            model_name='journaltable',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='express_anal_app.Shift', verbose_name='Смена'),
        ),
        migrations.AlterField(
            model_name='journaltable',
            name='time',
            field=models.DateTimeField(verbose_name='Время анализа/создания записи'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='arsenic',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='As'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='cd',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Cd'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='co',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Co'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Cu'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='cu_st1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Cu ст.1'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='current',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Выход по току'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Уд. вес'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='fe',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Fe'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='point',
            field=models.CharField(choices=[('0', 'ВСНС'), ('1', 'Ларокс'), ('2', 'Очищенный раствор'), ('3', 'Упр. несоответствия продукции')], max_length=1, verbose_name='Место измерения'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='sb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Sb'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='solid',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Твердое г\\л'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='solid_st1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Cd'),
        ),
        migrations.AlterField(
            model_name='productionerrors',
            name='correction',
            field=models.CharField(max_length=512, verbose_name='Коррекция'),
        ),
        migrations.AlterField(
            model_name='productionerrors',
            name='error',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Несоответствие'),
        ),
        migrations.AlterField(
            model_name='productionerrors',
            name='fact',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Факт'),
        ),
        migrations.AlterField(
            model_name='productionerrors',
            name='norm',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Норма'),
        ),
        migrations.AlterField(
            model_name='productionerrors',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='laborant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaching_shift_labornats', to='login_app.Employee', verbose_name='Лаборант'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaching_shift_masters', to='login_app.Employee', verbose_name='Мастер смены'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='order',
            field=models.DecimalField(decimal_places=0, max_digits=1, verbose_name='Номер смены (1, 2)'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='plant',
            field=models.CharField(choices=[('0', 'обжиг'), ('1', 'выщелачивание'), ('2', 'электролиз')], max_length=1, verbose_name='Цех'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
