# Generated by Django 2.0.2 on 2018-03-05 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('express_anal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agitators',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.Employee', verbose_name='Аппаратчик-гидрометаллург'),
        ),
        migrations.AddField(
            model_name='cinderdensity',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.Employee', verbose_name='Аппаратчик-гидрометаллург'),
        ),
        migrations.AddField(
            model_name='hydrometal',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.Employee', verbose_name='Аппаратчик-гидрометаллург'),
        ),
        migrations.AddField(
            model_name='shift',
            name='laborant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaching_shift_labornats', to='login_app.Employee', verbose_name='Лаборант'),
        ),
        migrations.AddField(
            model_name='shift',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaching_shift_masters', to='login_app.Employee', verbose_name='Мастер смены'),
        ),
    ]
