# Generated by Django 2.0.2 on 2018-03-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0002_auto_20180305_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='point',
            field=models.CharField(choices=[('0', 'lshs'), ('larox', 'Ларокс'), ('purified', 'Очищенный раствор'), ('prod_correction', 'Упр. Несоответствия продукции')], max_length=1, verbose_name='Место измерения'),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='stage',
            field=models.CharField(choices=[('1', '1ст'), ('2', '2ст'), ('3', '3ст'), ('cd', 'Сd'), ('empty', 'empty')], max_length=1),
        ),
        migrations.AlterField(
            model_name='shift',
            name='plant',
            field=models.CharField(choices=[('furnace', 'Обжиг'), ('leaching', 'Выщелачивание'), ('electrolysis', 'Электролиз')], max_length=1, verbose_name='Цех'),
        ),
    ]
