# Generated by Django 2.0.2 on 2018-03-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0003_auto_20180306_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denseranal',
            name='point',
            field=models.CharField(choices=[('10', 'Сгуститель №10'), ('11', 'Сгуститель №11'), ('12', 'Сгуститель №12')], max_length=1, verbose_name='Сгуститель №'),
        ),
        migrations.AlterField(
            model_name='denseranal',
            name='sink',
            field=models.CharField(choices=[('ls', 'ВС'), ('hs', 'НС')], max_length=1, verbose_name='Слив'),
        ),
    ]
