# Generated by Django 2.0.2 on 2018-03-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0004_auto_20180306_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denseranal',
            name='point',
            field=models.CharField(choices=[('10', 'Сгуститель №10'), ('11', 'Сгуститель №11'), ('12', 'Сгуститель №12')], max_length=20, verbose_name='Сгуститель №'),
        ),
        migrations.AlterField(
            model_name='denseranal',
            name='sink',
            field=models.CharField(choices=[('ls', 'ВС'), ('hs', 'НС')], max_length=5, verbose_name='Слив'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='point',
            field=models.CharField(choices=[('0', 'lshs'), ('larox', 'Ларокс'), ('purified', 'Очищенный раствор'), ('prod_correction', 'Упр. Несоответствия продукции')], max_length=20, verbose_name='Место измерения'),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='stage',
            field=models.CharField(choices=[('1', '1ст'), ('2', '2ст'), ('3', '3ст'), ('cd', 'Сd'), ('empty', 'empty')], max_length=20),
        ),
    ]
