# Generated by Django 2.0.2 on 2018-03-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0007_auto_20180306_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrometal',
            name='acid',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Кисл-ть'),
        ),
        migrations.AlterField(
            model_name='hydrometal',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Медь'),
        ),
        migrations.AlterField(
            model_name='hydrometal',
            name='fe2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Fe двухвал'),
        ),
        migrations.AlterField(
            model_name='hydrometal',
            name='fe_total',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Fe общее'),
        ),
        migrations.AlterField(
            model_name='hydrometal',
            name='mann_num',
            field=models.DecimalField(blank=True, choices=[(1, '1 Манн'), (4, '4 Манн')], decimal_places=5, max_digits=10, null=True, verbose_name='Манн №'),
        ),
        migrations.AlterField(
            model_name='hydrometal',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='hydrometal',
            name='sb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Сурьма'),
        ),
        migrations.AlterField(
            model_name='hydrometal',
            name='sediment',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Отстой'),
        ),
    ]
