# Generated by Django 2.0.2 on 2018-03-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0008_auto_20180307_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinderdensity',
            name='fe_avg',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Общее Fe среднее'),
        ),
        migrations.AlterField(
            model_name='cinderdensity',
            name='fe_shave',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Fe Стружка Fe'),
        ),
        migrations.AlterField(
            model_name='cinderdensity',
            name='gran',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Ситовой огарка'),
        ),
        migrations.AlterField(
            model_name='cinderdensity',
            name='gran_avg',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Ситовой огарка средний'),
        ),
        migrations.AlterField(
            model_name='hydrometal',
            name='mann_num',
            field=models.DecimalField(blank=True, choices=[(1, '1 Манн'), (4, '4 Манн')], decimal_places=0, max_digits=1, null=True, verbose_name='Манн №'),
        ),
    ]
