# Generated by Django 2.0.2 on 2018-03-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0009_auto_20180307_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='agitators',
            name='num',
            field=models.CharField(choices=[('13', '13, 14'), ('15', '15'), ('17', '17'), ('19', '19')], max_length=20, null=True, verbose_name='Агитатор'),
        ),
    ]
