# Generated by Django 2.0.2 on 2018-03-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0010_agitators_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agitators',
            name='comment',
            field=models.CharField(blank=True, max_length=128, verbose_name='Комментарий'),
        ),
    ]
