# Generated by Django 2.0.2 on 2018-03-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0011_auto_20180307_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agitators',
            name='cd',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Cd'),
        ),
        migrations.AlterField(
            model_name='agitators',
            name='co',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Co'),
        ),
        migrations.AlterField(
            model_name='agitators',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Cu'),
        ),
        migrations.AlterField(
            model_name='agitators',
            name='h2so4',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='H2SO4'),
        ),
        migrations.AlterField(
            model_name='agitators',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='pH'),
        ),
    ]
