# Generated by Django 2.0.2 on 2018-03-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0012_auto_20180307_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neutraldenser',
            name='liq_sol1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='neutraldenser',
            name='liq_sol2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='neutraldenser',
            name='sediment',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='plant',
            field=models.CharField(choices=[('furnace', 'обжиг'), ('leaching', 'выщелачивание'), ('electrolysis', 'электролиз')], max_length=10, verbose_name='Цех'),
        ),
    ]
