# Generated by Django 2.0.2 on 2018-03-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0015_auto_20180312_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetank',
            name='cur_measure',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='freetank',
            name='deviation',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='freetank',
            name='prev_measure',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='freetank',
            name='tank_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
