# Generated by Django 2.0.2 on 2018-03-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0016_auto_20180312_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetank',
            name='str_num',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
    ]
