# Generated by Django 2.0.2 on 2018-03-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0017_freetank_str_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetank',
            name='str_num',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
