# Generated by Django 2.0.2 on 2018-03-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0013_auto_20180312_1358'),
        ('express_anal_app', '0018_auto_20180312_1749'),
    ]

    operations = [
    ]
