# Generated by Django 2.0.2 on 2018-03-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0020_auto_20180312_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='neutralsolution',
            name='str_num',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='neutralsolution',
            name='tank_name',
            field=models.CharField(max_length=40),
        ),
    ]
