# Generated by Django 2.0.2 on 2018-03-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0021_auto_20180312_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neutralsolution',
            name='str_num',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
