# Generated by Django 2.0.2 on 2018-03-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0023_auto_20180312_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfsecurity',
            name='bignote',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='selfsecurity',
            name='note',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
