# Generated by Django 2.0.2 on 2018-03-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0024_auto_20180312_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schieht',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='schieht',
            name='num',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
