# Generated by Django 2.0.2 on 2018-03-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('express_anal_app', '0025_auto_20180312_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='JEACinder',
            fields=[
                ('journaltable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_anal_app.JournalTable')),
                ('col_num', models.DecimalField(decimal_places=0, max_digits=1)),
                ('shift_total', models.DecimalField(blank=True, decimal_places=5, max_digits=15)),
                ('day_total', models.DecimalField(blank=True, decimal_places=5, max_digits=15)),
                ('in_process', models.DecimalField(blank=True, decimal_places=5, max_digits=15)),
            ],
            bases=('express_anal_app.journaltable',),
        ),
        migrations.AddField(
            model_name='shiftinfo',
            name='furnaces',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='shiftinfo',
            name='next_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_shift_info', to='login_app.Employee', verbose_name='Мастер принял'),
        ),
        migrations.AddField(
            model_name='shiftinfo',
            name='this_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handed_over_shift_info', to='login_app.Employee', verbose_name='Мастер сдал'),
        ),
    ]
