# Generated by Django 2.0.2 on 2018-03-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0026_auto_20180313_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JEACinder',
            new_name='Cinder',
        ),
    ]
