# Generated by Django 2.0.2 on 2018-03-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0027_auto_20180313_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftinfo',
            name='free_13',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shiftinfo',
            name='free_13_t',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='shiftinfo',
            name='free_14',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shiftinfo',
            name='free_14_t',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
