# Generated by Django 2.0.2 on 2018-03-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0028_auto_20180313_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrolysis',
            name='comment',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='electrolysis',
            name='time1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrolysis',
            name='time2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrolysis',
            name='series',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
