# Generated by Django 2.0.2 on 2018-03-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0030_auto_20180313_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagents',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='reagents',
            name='consumption',
        ),
        migrations.RemoveField(
            model_name='reagents',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='reagents',
            name='mg',
        ),
        migrations.RemoveField(
            model_name='reagents',
            name='taken_away',
        ),
        migrations.RemoveField(
            model_name='reagents',
            name='zn',
        ),
        migrations.AddField(
            model_name='reagents',
            name='mg_ore',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reagents',
            name='state',
            field=models.CharField(choices=[('delivered', 'Доставлено'), ('taken', 'Принято'), ('consumption', 'Расход'), ('issued', 'Сдано')], default='delivered', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reagents',
            name='zn_dust',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='fe_shave',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='magnaglobe',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='shlippe',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='stage',
            field=models.CharField(choices=[('1st', '1ст'), ('2st', '2ст'), ('3st', '3ст'), ('cd', 'Cd'), ('total', 'Всего')], default='total', max_length=20),
        ),
    ]
