# Generated by Django 2.0.2 on 2018-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0031_auto_20180313_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='point',
            field=models.CharField(choices=[('lshs', 'ВСНС'), ('larox', 'Ларокс'), ('purified', 'Очищенный раствор'), ('prod_correction', 'Упр. Несоответствия продукции')], max_length=20, verbose_name='Место измерения'),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='state',
            field=models.CharField(choices=[('delivered', 'Доставлено'), ('taken', 'Принято'), ('consumption', 'Расход'), ('issued', 'Сдано'), ('none', 'Для стадий')], max_length=20),
        ),
    ]
