# Generated by Django 2.0.2 on 2018-03-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0032_auto_20180314_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='veu',
            name='num',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='point',
            field=models.CharField(choices=[('larox', 'Ларокс'), ('purified', 'Очищенный раствор'), ('prod_correction', 'Упр. Несоответствия продукции')], max_length=20, verbose_name='Место измерения'),
        ),
    ]
