# Generated by Django 2.0.2 on 2018-03-15 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0033_auto_20180314_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaltable',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время анализа/создания записи'),
        ),
    ]
