# Generated by Django 2.0.2 on 2018-03-15 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0034_auto_20180315_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='plant',
            field=models.CharField(choices=[('furnace', 'обжиг'), ('leaching', 'выщелачивание'), ('electrolysis', 'электролиз')], default=1, max_length=10, verbose_name='Цех'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journaltable',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='express_anal_app.Shift', verbose_name='Смена'),
        ),
    ]
