# Generated by Django 2.0.2 on 2018-03-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0036_auto_20180321_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='point',
            field=models.CharField(choices=[('lshs', 'ВСНС'), ('larox', 'Ларокс'), ('purified', 'Очищенный раствор'), ('prod_correction', 'Упр. Несоответствия продукции')], max_length=20, verbose_name='Место измерения'),
        ),
    ]
