# Generated by Django 2.0.2 on 2018-03-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0037_auto_20180322_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionerror',
            name='correction',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Коррекция'),
        ),
    ]
