# Generated by Django 2.0.3 on 2018-03-28 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0038_auto_20180326_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupulpanal',
            name='zn_pulp_anal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cu_pulp_anal', to='express_anal_app.ZnPulpAnal'),
        ),
        migrations.AddField(
            model_name='fesolutionanal',
            name='cu_pulp_anal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fe_solution_anal', to='express_anal_app.ZnPulpAnal'),
        ),
        migrations.AddField(
            model_name='fesolutionanal',
            name='zn_pulp_anal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fe_solution_anal', to='express_anal_app.CuPulpAnal'),
        ),
    ]
