# Generated by Django 2.0.3 on 2018-03-28 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0040_auto_20180328_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fesolutionanal',
            name='cu_pulp_anal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fe_solution_anal', to='express_anal_app.CuPulpAnal'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='zn_pulp_anal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fe_solution_anal', to='express_anal_app.ZnPulpAnal'),
        ),
    ]
