# Generated by Django 2.0.2 on 2018-03-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0041_auto_20180328_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupulpanal',
            name='after',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='После'),
        ),
        migrations.AlterField(
            model_name='cupulpanal',
            name='before',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='До'),
        ),
        migrations.AlterField(
            model_name='cupulpanal',
            name='liq_sol',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Ж:Т'),
        ),
        migrations.AlterField(
            model_name='cupulpanal',
            name='solid',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='ТВ'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='arsenic',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='As'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Cu'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Уд. вес'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='fe',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Fe'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='h2so4',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='H2SO4'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='sb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Sb'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='solid',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='ТВ'),
        ),
        migrations.AlterField(
            model_name='znpulpanal',
            name='liq_sol',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Ж:Т'),
        ),
        migrations.AlterField(
            model_name='znpulpanal',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='znpulpanal',
            name='t0',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='t0'),
        ),
    ]
