# Generated by Django 2.0.2 on 2018-04-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrolysis',
            name='loads1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='electrolysis',
            name='loads2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='electrolysis',
            name='series',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
