# Generated by Django 2.0.3 on 2018-04-09 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20180410_0105'),
        ('express_anal_app', '0002_auto_20180406_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='hydro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaching_shift_hydro', to='login_app.Employee', verbose_name='Аппаратчик-Гидрометаллург'),
        ),
    ]
