# Generated by Django 2.0.3 on 2018-04-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0003_shift_hydro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='plant',
            field=models.CharField(choices=[('furnace', 'Обжиг'), ('leaching', 'Выщелачивание'), ('electrolysis', 'Электролиз')], max_length=10, verbose_name='Цех'),
        ),
    ]
