# Generated by Django 2.0.3 on 2018-04-09 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0004_auto_20180410_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='hydro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaching_hydro_shifts', to='login_app.Employee', verbose_name='Аппаратчик-Гидрометаллург'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='laborant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaching_labornat_shifts', to='login_app.Employee', verbose_name='Лаборант'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaching_master_shifts', to='login_app.Employee', verbose_name='Мастер смены'),
        ),
    ]
