# Generated by Django 2.0.3 on 2018-04-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0005_auto_20180410_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='plant',
        ),
    ]
