# Generated by Django 2.0.3 on 2018-04-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0007_auto_20180412_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-date', '-order']},
        ),
    ]
