# Generated by Django 2.0.3 on 2018-04-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_anal_app', '0008_auto_20180412_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agitators',
            name='cd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cd'),
        ),
        migrations.AlterField(
            model_name='agitators',
            name='co',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Co'),
        ),
        migrations.AlterField(
            model_name='agitators',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cu'),
        ),
        migrations.AlterField(
            model_name='agitators',
            name='h2so4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='H2SO4'),
        ),
        migrations.AlterField(
            model_name='agitators',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='cinder',
            name='shift_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cinderdensity',
            name='fe_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общее Fe среднее'),
        ),
        migrations.AlterField(
            model_name='cinderdensity',
            name='fe_shave',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fe Стружка Fe'),
        ),
        migrations.AlterField(
            model_name='cinderdensity',
            name='gran',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ситовой огарка'),
        ),
        migrations.AlterField(
            model_name='cinderdensity',
            name='gran_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ситовой огарка средний'),
        ),
        migrations.AlterField(
            model_name='cupulpanal',
            name='after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='После'),
        ),
        migrations.AlterField(
            model_name='cupulpanal',
            name='before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='До'),
        ),
        migrations.AlterField(
            model_name='cupulpanal',
            name='liq_sol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ж:Т'),
        ),
        migrations.AlterField(
            model_name='cupulpanal',
            name='solid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ТВ'),
        ),
        migrations.AlterField(
            model_name='denseranal',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cu'),
        ),
        migrations.AlterField(
            model_name='denseranal',
            name='fe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fe'),
        ),
        migrations.AlterField(
            model_name='denseranal',
            name='liq_sol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ж:Т'),
        ),
        migrations.AlterField(
            model_name='denseranal',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='electrolysis',
            name='bunkers_furnace',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='electrolysis',
            name='bunkers_weltz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='electrolysis',
            name='counter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='electrolysis',
            name='silos_furnace',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='arsenic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='As'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='cl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Cl'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cu'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Уд. вес'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='fe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fe'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='h2so4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='H2SO4'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='sb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sb'),
        ),
        migrations.AlterField(
            model_name='fesolutionanal',
            name='solid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ТВ'),
        ),
        migrations.AlterField(
            model_name='freetank',
            name='cur_measure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='freetank',
            name='deviation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='freetank',
            name='prev_measure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hydrometal',
            name='acid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Кисл-ть'),
        ),
        migrations.AlterField(
            model_name='hydrometal',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Медь'),
        ),
        migrations.AlterField(
            model_name='hydrometal',
            name='fe2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fe двухвал'),
        ),
        migrations.AlterField(
            model_name='hydrometal',
            name='fe_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fe общее'),
        ),
        migrations.AlterField(
            model_name='hydrometal',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='hydrometal',
            name='sb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сурьма'),
        ),
        migrations.AlterField(
            model_name='hydrometal',
            name='sediment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Отстой'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='arsenic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='As'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='cd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cd'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='co',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Co'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cu'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='cu_st1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cu ст.1'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='current',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Выход по току'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Уд. вес'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='fe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fe'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='sb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sb'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='solid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Твердое г\\л'),
        ),
        migrations.AlterField(
            model_name='leachingexpressanal',
            name='solid_st1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cd'),
        ),
        migrations.AlterField(
            model_name='neutraldenser',
            name='liq_sol1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='neutraldenser',
            name='liq_sol2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='neutraldenser',
            name='sediment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='neutralsolution',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionerror',
            name='error',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Несоответствие'),
        ),
        migrations.AlterField(
            model_name='productionerror',
            name='fact',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Факт'),
        ),
        migrations.AlterField(
            model_name='productionerror',
            name='norm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Норма'),
        ),
        migrations.AlterField(
            model_name='readyproduct',
            name='cd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='readyproduct',
            name='co',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='readyproduct',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='readyproduct',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='readyproduct',
            name='fact',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='readyproduct',
            name='fe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='readyproduct',
            name='norm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='readyproduct',
            name='sb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='readyproduct',
            name='verified',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='readyproduct',
            name='vt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='fe_shave',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='magnaglobe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='mg_ore',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='shlippe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='zn_dust',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sample2',
            name='cd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sample2',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='schieht',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='free_13',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='free_14',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='in_fe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='in_fe_hi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='in_filtrate_dens',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='in_filtrate_ls',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='in_poor_cd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='out_cd_sponge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='out_cu_kek',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='out_cu_pulp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='out_electr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='out_neutr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='out_pulp_cvck',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='out_ruch_cd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='out_sol_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='out_sol_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='veu',
            name='cold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='veu',
            name='hot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='znpulpanal',
            name='liq_sol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ж:Т'),
        ),
        migrations.AlterField(
            model_name='znpulpanal',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='znpulpanal',
            name='t0',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='t0'),
        ),
    ]
