#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd /srv

touch /srv/logs/gunicorn.log
touch /srv/logs/access.log
tail -n 0 -f /srv/logs/*.log &

echo Starting Daphne...
exec daphne config.asgi:application \
    --bind 0.0.0.0 \
    --port 8001 \
    --verbosity 1 &

echo Starting Gunicorn...
exec gunicorn config.wsgi:application \
    --name e-logs \
    --bind "0.0.0.0:8002" \
    --workers 5 \
    --log-level=info \
    --log-file=/srv/logs/gunicorn.log \
    --access-logfile=/srv/logs/access.log


