# Generated by Django 2.0.4 on 2018-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='values',
            old_name='field_id',
            new_name='field_name',
        ),
        migrations.RemoveField(
            model_name='values',
            name='journal_name',
        ),
        migrations.AddField(
            model_name='objects',
            name='journal_name',
            field=models.CharField(default='', max_length=256, verbose_name='Название журнала'),
            preserve_default=False,
        ),
    ]
