# Generated by Django 2.0.5 on 2018-07-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalpage',
            name='shift_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала смены'),
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='shift_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер смены'),
        ),
    ]
