# Generated by Django 2.0.5 on 2018-07-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0002_auto_20180706_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='journalpage',
            name='equipment',
            field=models.CharField(max_length=256, null=True, verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='journalpage',
            name='month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Месяц'),
        ),
        migrations.AddField(
            model_name='journalpage',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
