# Generated by Django 2.0.5 on 2018-07-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0003_auto_20180706_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalpage',
            name='type',
            field=models.CharField(choices=[('shift', 'Смена'), ('equipment', 'Оборудование'), ('month', 'Месяц'), ('year', 'Год')], max_length=128),
        ),
    ]
