# Generated by Django 2.0.5 on 2018-07-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0003_auto_20180706_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='Тема')),
                ('text', models.CharField(max_length=1000, verbose_name='Сообщение')),
                ('plant', models.CharField(max_length=50, verbose_name='Цех')),
                ('journal', models.CharField(max_length=256, verbose_name='Журнал')),
                ('email', models.CharField(max_length=200, verbose_name='Почта')),
            ],
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='type',
            field=models.CharField(choices=[('shift', 'Смена'), ('equipment', 'Оборудование'), ('month', 'Месяц'), ('year', 'Год')], max_length=128),
        ),
    ]
