# Generated by Django 2.0.7 on 2018-07-12 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0003_auto_20180706_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cellvalue',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='journalpage',
            options={'verbose_name': 'Журнал', 'verbose_name_plural': 'Журналы'},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'verbose_name': 'Цех', 'verbose_name_plural': 'Цеха'},
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='all_journals_app.Plant', verbose_name='Цех'),
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='type',
            field=models.CharField(choices=[('shift', 'Смена'), ('equipment', 'Оборудование'), ('month', 'Месяц'), ('year', 'Год')], max_length=128, verbose_name='Тип'),
        ),
    ]
