# Generated by Django 2.0.4 on 2018-05-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0003_auto_20180516_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellvalue',
            name='value',
            field=models.CharField(max_length=1024, verbose_name='Значение поля'),
        ),
    ]
