# Generated by Django 2.0.4 on 2018-06-22 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0004_auto_20180516_1801'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cellvalue',
            unique_together={('journal_page', 'table_name', 'field_name', 'index')},
        ),
    ]
