# Generated by Django 2.0.4 on 2018-07-03 15:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_auto_20180623_1119'),
        ('all_journals_app', '0004_auto_20180516_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellvalue',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.Employee'),
        ),
        migrations.AddField(
            model_name='journalpage',
            name='plant',
            field=models.CharField(blank=True, choices=[('leaching', 'Выщелачивание'), ('furnace', 'Обжиг'), ('electrolysis', 'Электролиз')], default='leaching', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='journalpage',
            name='shift_date',
            field=models.DateField(blank=True, default=datetime.date(1999, 6, 15), null=True, verbose_name='Дата начала смены'),
        ),
        migrations.AddField(
            model_name='journalpage',
            name='shift_order',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Номер смены'),
        ),
    ]
