# Generated by Django 2.0.5 on 2018-07-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0004_auto_20180712_1112'),
        ('all_journals_app', '0005_feedback_username'),
    ]

    operations = [
    ]
