# Generated by Django 2.0.4 on 2018-07-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0005_auto_20180703_1551'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journalpage',
            unique_together={('plant', 'shift_order', 'shift_date', 'journal_name')},
        ),
    ]
