# Generated by Django 2.0.4 on 2018-07-04 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0006_auto_20180703_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('leaching', 'Выщелачивание'), ('furnace', 'Обжиг'), ('electrolysis', 'Электролиз')], default='leaching', max_length=128, null=True)),
                ('number_of_shifts', models.IntegerField(blank=True, default=1, null=True, verbose_name='Количестов смен')),
            ],
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='all_journals_app.Plant'),
        ),
    ]
