# Generated by Django 2.1.2 on 2018-11-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldconstraints',
            name='max_normal',
            field=models.IntegerField(default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fieldconstraints',
            name='min_normal',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
