# Generated by Django 2.1 on 2018-09-03 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0004_shift_closed'),
        ('modes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_journals_app.Journal'),
        ),
    ]
