# Generated by Django 2.1 on 2018-09-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modes', '0002_mode_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
