# Generated by Django 2.1.2 on 2018-11-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modes', '0002_auto_20181112_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldconstraints',
            name='max_normal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fieldconstraints',
            name='min_normal',
            field=models.IntegerField(null=True),
        ),
    ]
