# Generated by Django 2.0.5 on 2018-07-06 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('position', models.CharField(blank=True, choices=[('master', 'Мастер'), ('laborant', 'Лаборант'), ('hydro', 'Аппаратчик-гидрометаллург'), ('admin', 'Админ'), ('boss', 'Начальник цеха')], max_length=128)),
                ('plant', models.CharField(choices=[('furnace', 'Обжиг'), ('leaching', 'Выщелачивание'), ('electrolysis', 'Электролиз')], max_length=10, null=True, verbose_name='Цех')),
                ('csrf', models.CharField(default=' ', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('type', models.CharField(choices=[('critical_value', 'Критическое значение'), ('note', 'Замечание')], max_length=100, null=True, verbose_name='Тип сообщения')),
                ('cell_field_name', models.CharField(default=None, max_length=128, null=True, verbose_name='Название поля ячейки')),
                ('cell_table_name', models.CharField(default=None, max_length=128, null=True, verbose_name='Название таблицы ячейки')),
                ('cell_journal_page', models.IntegerField(blank=True, default=None, null=True, verbose_name='Номер журнала ячейки')),
                ('row_index', models.IntegerField(blank=True, default=None, null=True, verbose_name='Номер строчки ячейки')),
                ('addressee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='login_app.Employee')),
            ],
        ),
    ]
