# Generated by Django 2.0.5 on 2018-07-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0001_initial'),
        ('login_app', '0002_auto_20180706_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='owned_journal_pages',
            field=models.ManyToManyField(blank=True, to='all_journals_app.JournalPage'),
        ),
    ]
