# Generated by Django 2.0.3 on 2018-04-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_employee_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='plant',
            field=models.CharField(choices=[('furnace', 'Обжиг'), ('leaching', 'Выщелачивание'), ('electrolysis', 'Электролиз')], max_length=10, null=True, verbose_name='Цех'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('master', 'Мастер'), ('laborant', 'Лаборант'), ('hydro', 'Аппаратчик-гидрометаллург'), ('admin', 'Админ'), ('boss', 'Начальник цеха')], max_length=128),
        ),
    ]
