# Generated by Django 2.0.3 on 2018-04-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='position',
        ),
    ]
