# Generated by Django 2.0.4 on 2018-04-18 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_remove_message_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='addressee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='login_app.Employee'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('critical_value', 'Критическое значение'), ('note', 'Замечание')], max_length=100, null=True, verbose_name='Тип сообщения'),
        ),
    ]
