# Generated by Django 2.0.6 on 2018-06-23 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0004_auto_20180516_1801'),
        ('login_app', '0006_auto_20180418_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='all_journals_app.CellValue'),
        ),
    ]
