# Generated by Django 2.0.6 on 2018-06-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_message_cell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='cell',
        ),
        migrations.AddField(
            model_name='message',
            name='cell_field_name',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Название поля ячейки'),
        ),
        migrations.AddField(
            model_name='message',
            name='cell_journal_page',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Номер журнала ячейки'),
        ),
        migrations.AddField(
            model_name='message',
            name='cell_table_name',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Название таблицы ячейки'),
        ),
        migrations.AddField(
            model_name='message',
            name='row_index',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Номер строчки ячейки'),
        ),
    ]
