# Generated by Django 2.0.4 on 2018-07-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_journals_app', '0005_auto_20180703_1551'),
        ('login_app', '0008_auto_20180623_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='owned_journal_pages',
            field=models.ManyToManyField(to='all_journals_app.JournalPage'),
        ),
    ]
