# Generated by Django 2.0.4 on 2018-07-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0009_employee_owned_journal_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='csrf',
            field=models.CharField(default=' ', max_length=32),
        ),
        migrations.AlterField(
            model_name='employee',
            name='owned_journal_pages',
            field=models.ManyToManyField(blank=True, to='all_journals_app.JournalPage'),
        ),
    ]
